### ISSUE TITLE
Cannot craft some items

### ISSUE THREAD

**Issue by samsonsin** [NeroOneTrueKing/auto-stocker#1]
Hello!

Im currently playing GT:NH and have been looking for a good autostocker program i can use! So far, yours comes out on top, but I've not gotten it to work with a select few items. Namely, AE2 Fluid Crafting fluids.

If i try to set a stock for them, the autostocker finds every single fluid that is craftable in the network, and unpredictably crafts some of them.  I believe this is because the program filters based on the "name" and "damage" of the item in question. However, this is a problem since some items share this name.

The entry in the StockFile.txt of the item im trying to craft looks like this:
`{["ae2fc:fluid_drop:0"]={["groupsize"]=1000,["stockquan"]=1000,["label"]="drop of Molten Polybenzimidazole",["name"]="ae2fc:fluid_drop",["damage"]=0}}`

![image](https://user-images.githubusercontent.com/23201902/214169074-0cf66b93-adfb-430d-817e-9e707467b1f4.png)
![image](https://user-images.githubusercontent.com/23201902/214169199-d094dadb-a2a9-4883-9915-9931e7a7e7fc.png)

Using the Label might be more appropriate. What do you think?

Thank you for your time!

**Comment by samsonsin** [comment]
![image](https://user-images.githubusercontent.com/23201902/214170417-3432e14e-a1ae-4730-8997-9b9309f6e4e5.png)

**Comment by samsonsin** [comment]
if i simply change all occurences of ".name" to ".label" this flickers on the side: 
![image](https://user-images.githubusercontent.com/23201902/214171677-b70b54be-d7ae-4f6d-acbb-c67755e7402f.png)
This is the correct amount present in my system. So doing this seems to at least filter that part of the screen.
![image](https://user-images.githubusercontent.com/23201902/214172018-06c58f44-df49-48c9-ada1-0996fecb9e55.png)
I wouldnt expect this to work though, which it doesnt. When the queued item goes to craft:
![image](https://user-images.githubusercontent.com/23201902/214172170-d7b5e041-396f-4b26-892a-d4083ec5e040.png)

Codebase is quite alien to me sadly. Ill have a look on my own to see if i can solve this. However, if you are able, could you help me out?

**Comment by samsonsin** [comment]
![image](https://user-images.githubusercontent.com/23201902/214173306-d3af3ca8-24d6-4a17-a5f4-e5e5fde459c0.png)
Well honestly that was easier than i expected. Changing all the occurences of .name (and making sure that some of the crafting requesting stuff also used the label rather than name) resulted in it working, i think.

Again, i am quite unfamiliar with the codebase. Its shocking that this /seems/ to work, but i am assuming that something can break down the line. Also, if you do intend to keep this repo up to date then you could probably fix. I assume using label would perhaps break if localization between server & client doesnt match, so this might not be the most elegant solution either.

Of note is that line 75 error still occurs occasionally. It seems to be sending "lineNumber" as 2, while the item in question rests on line 1... Can avoid this issue to some extent by not pressing anything on the left side, though. Also, entries in both left and right sides seem to display contents, then stop doing so, on a loop.

**Comment by NeroOneTrueKing** [comment]
Interesting! I got off of GT:NH for a while and am just restarting now; I never tried AE2 fluids. I think at the time the only option was volumetric flasks, and I didn't attempt to stock those.

Since my current playthrough isn't at the point where I'm using this script yet, I don't intend on actively maintaining this script for now -- I'd rather play my active game than debug OC in a creative singleplayer world. When I get to a tier to use this again, I'll start actively maintaining it.

However, I will happily merge any pull request bugfixes or features! I'm very happy someone else is enjoying my program.

**Comment by NeroOneTrueKing** [comment]
Fixed in the new release!

**Comment by samsonsin** [comment]
Nice! I took a break a few weeks after I raised this issue, and will probs resume in a few weeks myself. Thanks for your hard work!
